mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.33.10:3306/memorn_mall_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: memorn-member
server:
  port: 6001